updated login and signup page
Priyansh61/BSoC pull request #18
Opened 2023-05-26 22:50 UTC by tushitshukla03

2023-05-27 07:34 UTC, Priyansh61 requested changes
![image](https://github.com/Priyansh61/BSoC/assets/96513964/079d3542-3f81-40ef-89ce-bf121f241f30)


1. I guess the card is not in the center. Could you please check that ?
2. Remove the naming login form just keep it login 
3. Same, just keep the other signup
4. Keep the login/signup with google at top then add or for other options

2023-05-27 07:34 UTC, Priyansh61 commented on src/assets/Group 1f1.png
We dont need this ig

2023-05-27 07:34 UTC, Priyansh61 commented on src/assets/Group 2f2.png
This is also not needed.

2023-05-27 07:34 UTC, Priyansh61 commented on src/assets/Group 4f3.png
Same here

2023-05-28 08:33 UTC, tushitshukla03 commented
> ![image](https://user-images.githubusercontent.com/96513964/241366439-079d3542-3f81-40ef-89ce-bf121f241f30.png)
> 
> 1. I guess the card is not in the center. Could you please check that ?
> 2. Remove the naming login form just keep it login
> 3. Same, just keep the other signup
> 4. Keep the login/signup with google at top then add or for other options

please check now

2023-05-28 08:41 UTC, merged